name: CI - Loja Veloz

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do c√≥digo
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ===== ORDERS =====
      - name: Build & Push Orders
        uses: docker/build-push-action@v5
        with:
          context: ./services/orders
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/orders:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/orders:1.0.0

      # ===== INVENTORY =====
      - name: Build & Push Inventory
        uses: docker/build-push-action@v5
        with:
          context: ./services/inventory
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/inventory:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/inventory:1.0.0

      # ===== PAYMENTS =====
      - name: Build & Push Payments
        uses: docker/build-push-action@v5
        with:
          context: ./services/payments
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/payments:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/payments:1.0.0
